// Para requisições com body:
// Content-Type: application/json

// Para requisições com headers: 
// Authorization: "token"


###
GET http://localhost:3003/teste


###
GET http://localhost:3003/users

###
GET http://localhost:3003/users/normal






###
# GET http://localhost:3003/users/50

# ###
# POST http://localhost:3003/users
# Content-Type: application/json

# {
#     "id": 50,
#     "name": "rod",
#     "email": "email@email",
#     "type": "NORMAL",
#     "age": 32
# }

# ###
# PATCH http://localhost:3003/users
# Content-Type: application/json

# {
#     "id": 50,
#     "name": "rod",
#     "email": "email@email",
#     "type": "NORMAL",
#     "age": 33
# }