
###
GET http://localhost:3003/actors/11


###
GET http://localhost:3003/actors?gender=female

###
POST http://localhost:3003/actor
Content-Type:  application/json

{
    "name": "Crocôdilo do Pântano",
    "salary": 500000,
    "birthDate": "2002-02-02",
    "gender": "male"
}


###
PUT http://localhost:3003/actor
Content-Type:  application/json

{
    "id": 11,
    "salary": 25252520000
}


###
DELETE http://localhost:3003/actor/7













// Exercicio anterior

###
GET http://localhost:3003/actor


###
POST http://localhost:3003/actor
Content-Type:  application/json

{
    "name": "Gabriel Silva",
    "salary": 500000,
    "birthDate": "1998-02-23",
    "gender": "male"
}


###
PUT http://localhost:3003/actor/11
Content-Type:  application/json

{
    "salary": 320000000
}


###
DELETE  http://localhost:3003/actor/6